### ISSUE TITLE
Block non-admin users from certain requests

### ISSUE THREAD

**Issue by ValerianClerc** [Compete-McGill/wisp-users-microservice#14]
Together with the gateway, limit access to backend routes so the "USER" role tokens can only access the:
* GET routes
* PUT routes for their own user model

**Comment by MohamedBeydoun** [comment]
Opened issue in wisp-gateway. Only change in wisp-users is to send the user role in the introspection response.

**Comment by MohamedBeydoun** [comment]
/auth/introspect already returns the user's role
