### ISSUE TITLE
Platform Data is not returned on User endpoints.

### ISSUE THREAD

**Issue by imad-ant** [Compete-McGill/wisp-users-microservice#24]
Platform Data is not returned on show, index, create, update and delete endpoint responses.

Possible reason is that our user interface requires "email" and "lastSubmission" data to be present for this to be returned (not confirmed).

**Comment by MohamedBeydoun** [comment]
empty fields in the user model should be set to default values to avoid this kind of issue e.g.
```javascript
{
    ....
    platformData: {
        codeforces: {
            username: "some-name",
            email: "",
            lastSubmission: null,
        }
    }
}
```

See user.role in the user model for how to define a default value.
